version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:


 angular: # name of the first service
  build:  DATA-LABELING-FRONT-END # specify the directory of the Dockerfile
  links:
  - node
  ports:
  - "4200:4200" # specify port mapping
  #volumes:
  #- /app/dist/data-labeling-front-end:/usr/share/nginx/html
  #- /app/data-labeling-front-end/node_modules
 node: # name of the second service
  build: DATA-LABELING-BACK-END # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - database # link this service to the database service
  - dextr
  - angular
  #volumes:
  #- /usr/src/app:/app/data-labeling-back-end
  #- /usr/src/app/data-labeling-back-end/node_modules

 database: # name of the third service
  image: mongo # specify image to build container from
  environment:
    MONGO_INITDB_ROOT_USERNAME: unfraudedadmin
    MONGO_INITDB_ROOT_PASSWORD: unfraudedadmin
    MONGO_INITDB_DATABASE: data-labeling
  ports:
  - "27017:27017" # specify port forwarding
  volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro



 dextr: # name of the third service
  build: DEXTR # specify the directory of the Dockerfile
  ports:
  - "5000:5000" # specify port mapping
